export PATH="~/.cabal/bin/:$PATH"
export TERM="xterm-256color"
export ZSH=~/.oh-my-zsh

POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir_writable dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)

POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND=cyan
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=cyan
POWERLEVEL9K_CONTEXT_SUDO_BACKGROUND=cyan
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND=cyan
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND=cyan

POWERLEVEL9K_DIR_HOME_FOREGROUND="black"
POWERLEVEL9K_DIR_HOME_BACKGROUND="cyan"

POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="black"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="cyan"

POWERLEVEL9K_DIR_ETC_FOREGROUND="black"
POWERLEVEL9K_DIR_ETC_BACKGROUND="cyan"

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="black"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="cyan"

POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="black"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="red"

POWERLEVEL9K_VCS_CLEAN_FOREGROUND="yellow"
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="black"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="black"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="yellow"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="black"

POWERLEVEL9K_STATUS_FOREGROUND="red"

ZSH_THEME="powerlevel9k/powerlevel9k"

plugins=(git command-not-found cabal pip)

source $ZSH/oh-my-zsh.sh

COMPLETION_WAITING_DOTS="true"

. ~/z.sh

alias lsd="ls -ld .*"
alias zs="source ~/.zshrc"
alias vizsh="vi ~/.zshrc"
alias vivim="vi ~/.vim/vimrc"
alias dit='/usr/bin/git --git-dir=~/.cfg/ --work-tree=~/'
#
ENABLE_CORRECTION="true"
